$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path | Split-Path -Parent
$SourceWorkbook = Join-Path $ProjectRoot "output\自动化经营报表.xlsx"
$TargetWorkbook = Join-Path $ProjectRoot "output\自动化经营报表-含PowerQuery.xlsx"
$QueryDir = Join-Path $ProjectRoot "powerquery\queries"
$Description = "Automated operating report query generated by the portfolio project"

$excel = $null
$workbook = $null
try {
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false
    $excel.AskToUpdateLinks = $false
    $workbook = $excel.Workbooks.Open($SourceWorkbook, $false, $false)

    foreach ($queryFile in Get-ChildItem -LiteralPath $QueryDir -Filter "*.pq" | Sort-Object Name) {
        $name = $queryFile.BaseName
        $formula = Get-Content -Raw -LiteralPath $queryFile.FullName
        $existing = $null
        foreach ($query in $workbook.Queries) {
            if ($query.Name -eq $name) { $existing = $query; break }
        }
        if ($existing -ne $null) { $existing.Formula = $formula; $existing.Description = $Description }
        else { [void]$workbook.Queries.Add($name, $formula, $Description) }
    }

    $workbook.SaveAs($TargetWorkbook, 51)
    $summary = @{
        workbook = $TargetWorkbook
        queryCount = $workbook.Queries.Count
        queries = @($workbook.Queries | ForEach-Object { $_.Name })
    }
    $summary | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath (Join-Path $ProjectRoot "output\powerquery_embed_report.json") -Encoding utf8
    $workbook.Close($true)
    $excel.Quit()
    $summary | ConvertTo-Json -Depth 4
}
finally {
    if ($workbook -ne $null) { [void][Runtime.InteropServices.Marshal]::ReleaseComObject($workbook) }
    if ($excel -ne $null) { [void][Runtime.InteropServices.Marshal]::ReleaseComObject($excel) }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()
}